###
#* INSTRUCTIONS *#
# 1. Update this file with your own values.
# 2. Rename this file to docker-compose.override.yml.
# 3. Run `docker compose up -d` to start the services.
#    If you are using additional compose files, use:
#    `docker compose -f docker-compose.yml -f docker-compose.override.yml up -d`
###

name: <YOUR-STACK-NAME>

services:
  ###
  #! Bookmarks !#
  # https://github.com/pgvector/pgvector
  # https://hub.docker.com/r/pgvector/pgvector/tags
  # https://github.com/robsoncombr/fk-pgvector
  # https://github.com/robsoncombr/rbs-pgvector
  ###
  pgvector:
    #image: pgvector/pgvector:latest
    image: pgvector/pgvector:<YOUR-TAG>
    container_name: pgvector
    hostname: pgvector
    networks:
      - network
    ports:
      - "<YOUR-PRIVATE-IP>:<YOUR-EXPOSED-PORT>:5432"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./volumes/dump:/var/lib/postgresql/dump

networks:
  network:
    name: <YOUR-NETWORK-NAME>
    driver: bridge
    #external: true
