name: production-databank

services:
  ###
  #! Bookmarks !#
  # https://github.com/pgvector/pgvector
  # https://hub.docker.com/r/pgvector/pgvector/tags
  # https://github.com/robsoncombr/fk-pgvector
  # https://github.com/robsoncombr/rbs-pgvector
  ###
  pgvector:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PG_MAJOR=17
    #image: pgvector/pgvector:latest
    #image: pgvector/pgvector:0.8.0-pg17
    image: gru.ocir.io/gr2citfeoa4x/rbs-pgvector:0.8.0-pg17-geo
    container_name: pgvector
    hostname: pgvector
    networks:
      - network
    ports:
      - "172.16.0.155:5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./volumes/data:/var/lib/postgresql/data
      - ./volumes/dump:/var/lib/postgresql/dump

networks:
  network:
    name: production-network
    driver: bridge
    external: true
